server:
  port: 8081
  servlet:
    context-path: /customer_finance


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_db
    username: admin
    password: iV$8%Omr
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.connection.isolation: 2 # 2 = READ COMMITTED
      hibernate.default_schema: finance
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: liquebase

jwt:
  secret: GVN0GW/NDhnUnFRu9G8a1LhFH8A65nEWRrvNd93I4mc=
  acccess-token-expiration: 1800000
  refresh-token-expiration: 86400000    # Токен живет 1 дней

logging:
  level:
    org.springframework.security: DEBUG

